import { getStore } from '@netlify/blobs';
import { randomBytes,scryptSync,timingSafeEqual,createHmac } from 'node:crypto';
const seed=[
 {username:'KAI',playerName:'Kai Lucas',playerId:'kai-lucas',memberId:'TC-001',memberSince:'2026',status:'Tour Member',cardLevel:'Member',validThrough:''},
 {username:'FLETCHER',playerName:'Fletcher Gaffney',playerId:'fletcher-gaffney',memberId:'TC-002',memberSince:'2026',status:'Tour Member',cardLevel:'Member',validThrough:''},
 {username:'XAVIER',playerName:'Xavier Minogue',playerId:'xavier-minogue',memberId:'TC-003',memberSince:'2026',status:'Tour Member',cardLevel:'Member',validThrough:''},
 {username:'ANDRE',playerName:'Andre',playerId:'',memberId:'TC-004',memberSince:'2026',status:'Tour Member',cardLevel:'Member',validThrough:''}];
function adminOk(req){const cookie=req.headers.get('cookie')||'';const m=cookie.match(/(?:^|;\s*)tt_admin=([^;]+)/);const s=process.env.ADMIN_SESSION_SECRET;if(!m||!s)return false;const x=createHmac('sha256',s).update('travellers-admin-v1').digest('base64url');return timingSafeEqual(Buffer.from(m[1]),Buffer.from(x))}
const safe=a=>({username:a.username,playerName:a.playerName||'',playerId:a.playerId||'',memberId:a.memberId||'',memberSince:a.memberSince||'',status:a.status||'Tour Member',cardLevel:a.cardLevel||'Member'});
function hashPassword(p){const salt=randomBytes(16).toString('hex');const hash=scryptSync(p,salt,64).toString('hex');return {passwordSalt:salt,passwordHash:hash}}
async function accounts(){const store=getStore({name:'travellers-tour-members',consistency:'strong'});let arr=await store.get('accounts',{type:'json',consistency:'strong'});if(!arr)arr=[];for(const s of seed){if(!arr.some(a=>a.username===s.username))arr.push({...s})}return {store,arr}}
export default async req=>{if(!adminOk(req))return new Response('Unauthorized',{status:401});const {store,arr}=await accounts();if(req.method==='GET')return new Response(JSON.stringify(arr.map(safe)),{headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});if(req.method!=='POST')return new Response('Method not allowed',{status:405});const body=await req.json();const username=String(body.username||'').trim().toUpperCase();if(!username)return new Response('Username required',{status:400});if(body.action==='create'){if(arr.some(a=>a.username===username))return new Response('Username already exists',{status:400});if(!body.newPassword)return new Response('Initial password required',{status:400});arr.push({username,playerName:'',playerId:body.playerId||'',memberId:body.memberId||'',memberSince:body.memberSince||'',status:body.status||'Tour Member',cardLevel:body.cardLevel||'Member',...hashPassword(body.newPassword)})}else{const a=arr.find(x=>x.username===username);if(!a)return new Response('Member not found',{status:404});a.playerId=body.playerId??a.playerId;a.memberId=body.memberId??a.memberId;a.memberSince=body.memberSince??a.memberSince;a.status=body.status??a.status;a.cardLevel=body.cardLevel??a.cardLevel;if(body.newPassword)Object.assign(a,hashPassword(body.newPassword))}await store.setJSON('accounts',arr);return new Response(JSON.stringify({ok:true}),{headers:{'Content-Type':'application/json'}})};