let DATA=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const slug=s=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+Date.now();
async function api(path,opts={}){const r=await fetch('/.netlify/functions/'+path,opts);if(r.status===401)throw new Error('AUTH');if(!r.ok)throw new Error(await r.text());const ct=r.headers.get('content-type')||'';return ct.includes('json')?r.json():r.text()}
async function load(){DATA=await api('data',{cache:'no-store'});render()}
async function save(){await api('data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(DATA)});await load()}
async function upload(input){if(!input.files[0])return '';const fd=new FormData();fd.append('file',input.files[0]);const r=await api('upload',{method:'POST',body:fd});return r.url}
function render(){cName.value=DATA.champion.name;cEvent.value=DATA.champion.event;cScore.value=DATA.champion.score||'';epSelect.innerHTML=DATA.players.map((p,i)=>`<option value="${i}">${esc(p.name)}</option>`).join('');loadPlayer();renderTournaments();renderRecords()}
function loadPlayer(){const p=DATA.players[+epSelect.value||0];if(!p)return;epStatus.value=p.status||'Tour Member';epPoints.value=p.points||0;epWins.value=p.wins||0;epSeconds.value=p.seconds||0;epMajors.value=p.majors||0;epMvp.value=p.mvp||0;epBio.value=p.bio||'';epLongBio.value=p.longBio||''}
function renderTournaments(){tournamentAdminList.innerHTML=DATA.tournaments.map((t,i)=>`<div class="admin-list-item"><div><strong>${esc(t.name)}</strong><br><span class="meta">${esc(t.status)} · ${esc(t.date)}</span></div><div class="actions">${t.status!=='completed'?`<button class="button done" data-i="${i}">Done</button>`:`<button class="secondary-button undo" data-i="${i}">Move to upcoming</button>`}<button class="danger-button del-t" data-i="${i}">Delete</button></div></div>`).join('');document.querySelectorAll('.done').forEach(b=>b.onclick=async()=>{const i=+b.dataset.i;DATA.tournaments[i].winner=prompt('Winner:',DATA.tournaments[i].winner||'')||'';DATA.tournaments[i].score=prompt('Winning score/result:',DATA.tournaments[i].score||'')||'';DATA.tournaments[i].status='completed';await save()});document.querySelectorAll('.undo').forEach(b=>b.onclick=async()=>{DATA.tournaments[+b.dataset.i].status='upcoming';await save()});document.querySelectorAll('.del-t').forEach(b=>b.onclick=async()=>{if(confirm('Delete tournament?')){DATA.tournaments.splice(+b.dataset.i,1);await save()}})}
function renderRecords(){recordsAdminList.innerHTML=DATA.records.map((r,i)=>`<div class="admin-list-item"><div><strong>${esc(r.title)}</strong><br><span class="meta">${esc(r.description)}</span></div><button class="danger-button del-r" data-i="${i}">Delete</button></div>`).join('');document.querySelectorAll('.del-r').forEach(b=>b.onclick=async()=>{if(confirm('Delete record?')){DATA.records.splice(+b.dataset.i,1);await save()}})}
loginForm.onsubmit=async e=>{e.preventDefault();try{await api('login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:adminPassword.value})});loginGate.hidden=true;adminContent.hidden=false;await load()}catch{loginError.hidden=false}}
async function check(){try{await api('auth');loginGate.hidden=true;adminContent.hidden=false;await load()}catch{}}
championForm.onsubmit=async e=>{e.preventDefault();DATA.champion={...DATA.champion,name:cName.value.trim(),event:cEvent.value.trim(),score:cScore.value.trim()};const u=await upload(cImage);if(u)DATA.champion.image=u;await save();alert('Champion saved.')}
addPlayerForm.onsubmit=async e=>{e.preventDefault();const img=await upload(pImage);DATA.players.push({id:slug(pName.value),name:pName.value.trim(),status:pStatus.value.trim()||'Tour Member',points:+pPoints.value||0,wins:+pWins.value||0,seconds:+pSeconds.value||0,majors:+pMajors.value||0,mvp:+pMvp.value||0,image:img,bio:pBio.value.trim(),longBio:pLongBio.value.trim()});await save();e.target.reset();pStatus.value='Tour Member';alert('Player added.')}
epSelect.onchange=loadPlayer;
editPlayerForm.onsubmit=async e=>{e.preventDefault();const p=DATA.players[+epSelect.value];p.status=epStatus.value.trim();p.points=+epPoints.value||0;p.wins=+epWins.value||0;p.seconds=+epSeconds.value||0;p.majors=+epMajors.value||0;p.mvp=+epMvp.value||0;p.bio=epBio.value.trim();p.longBio=epLongBio.value.trim();const img=await upload(epImage);if(img)p.image=img;await save();alert('Player saved.')}
deletePlayer.onclick=async()=>{const i=+epSelect.value;if(confirm('Delete player?')){DATA.players.splice(i,1);await save()}}
tournamentForm.onsubmit=async e=>{e.preventDefault();const img=await upload(tImage);DATA.tournaments.push({id:slug(tName.value),name:tName.value.trim(),course:tCourse.value.trim(),date:tDate.value,type:tType.value,status:tStatus.value,winner:tWinner.value.trim(),score:tScore.value.trim(),image:img});if(img)DATA.gallery.unshift(img);await save();e.target.reset();alert('Tournament added.')}
newsForm.onsubmit=async e=>{e.preventDefault();const img=await upload(nImage);DATA.news.push({id:slug(nHeadline.value),headline:nHeadline.value.trim(),date:nDate.value,summary:nSummary.value.trim(),body:nBody.value.trim(),image:img});await save();e.target.reset();alert('Article published.')}
recordForm.onsubmit=async e=>{e.preventDefault();DATA.records.push({id:slug(rTitle.value),title:rTitle.value.trim(),description:rDescription.value.trim()});await save();e.target.reset();alert('Record added.')}
shopForm.onsubmit=async e=>{e.preventDefault();const img=await upload(sImage);DATA.shop.push({id:slug(sName.value),name:sName.value.trim(),price:sPrice.value.trim(),description:sDescription.value.trim(),link:sLink.value.trim(),image:img});await save();e.target.reset();alert('Shop item added.')}
galleryForm.onsubmit=async e=>{e.preventDefault();const img=await upload(gImage);if(img){DATA.gallery.unshift(img);await save();e.target.reset();alert('Graphic added.')}}
check();
