let DATA=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const slug=s=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+Date.now();
async function api(path,opts={}){const r=await fetch('/.netlify/functions/'+path,opts);if(r.status===401)throw new Error('AUTH');if(!r.ok)throw new Error(await r.text());const ct=r.headers.get('content-type')||'';return ct.includes('json')?r.json():r.text()}
let MEMBERS=[];async function load(){DATA=await api('data',{cache:'no-store'});DATA.polls=DATA.polls||[];DATA.attendance=DATA.attendance||{};try{MEMBERS=await api('members',{cache:'no-store'})}catch{MEMBERS=[]}render()}
async function save(){await api('data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(DATA)});await load()}
async function upload(input){if(!input.files[0])return '';const fd=new FormData();fd.append('file',input.files[0]);const r=await api('upload',{method:'POST',body:fd});return r.url}
function render(){cName.value=DATA.champion.name;cEvent.value=DATA.champion.event;cScore.value=DATA.champion.score||'';epSelect.innerHTML=DATA.players.map((p,i)=>`<option value="${i}">${esc(p.name)}</option>`).join('');enSelect.innerHTML=DATA.news.map((n,i)=>`<option value="${i}">${esc(n.headline)}</option>`).join('');esSelect.innerHTML=DATA.shop.map((s,i)=>`<option value="${i}">${esc(s.name)}</option>`).join('');loadPlayer();loadNews();loadShop();renderTournaments();renderRecords();renderPolls();renderMembers()}
function loadPlayer(){const p=DATA.players[+epSelect.value||0];if(!p)return;epStatus.value=p.status||'Tour Member';epPoints.value=p.points||0;epWins.value=p.wins||0;epSeconds.value=p.seconds||0;epMajors.value=p.majors||0;epMvp.value=p.mvp||0;epBio.value=p.bio||'';epLongBio.value=p.longBio||''}
function loadNews(){const n=DATA.news[+enSelect.value||0];if(!n){enHeadline.value='';enDate.value='';enSummary.value='';enBody.value='';return}enHeadline.value=n.headline||'';enDate.value=n.date||'';enSummary.value=n.summary||'';enBody.value=n.body||''}
function loadShop(){const s=DATA.shop[+esSelect.value||0];if(!s){esName.value='';esPrice.value='';esLink.value='';esDescription.value='';return}esName.value=s.name||'';esPrice.value=s.price||'';esLink.value=s.link||'';esDescription.value=s.description||''}
function renderTournaments(){tournamentAdminList.innerHTML=DATA.tournaments.map((t,i)=>`<div class="admin-list-item"><div><strong>${esc(t.name)}</strong><br><span class="meta">${esc(t.status)} · ${esc(t.date)}</span></div><div class="actions">${t.status!=='completed'?`<button class="button done" data-i="${i}">Done</button>`:`<button class="secondary-button undo" data-i="${i}">Move to upcoming</button>`}<button class="danger-button del-t" data-i="${i}">Delete</button></div></div>`).join('');document.querySelectorAll('.done').forEach(b=>b.onclick=async()=>{const i=+b.dataset.i;DATA.tournaments[i].winner=prompt('Winner:',DATA.tournaments[i].winner||'')||'';DATA.tournaments[i].score=prompt('Winning score/result:',DATA.tournaments[i].score||'')||'';DATA.tournaments[i].status='completed';await save()});document.querySelectorAll('.undo').forEach(b=>b.onclick=async()=>{DATA.tournaments[+b.dataset.i].status='upcoming';await save()});document.querySelectorAll('.del-t').forEach(b=>b.onclick=async()=>{if(confirm('Delete tournament?')){DATA.tournaments.splice(+b.dataset.i,1);await save()}})}
function renderRecords(){recordsAdminList.innerHTML=DATA.records.map((r,i)=>`<div class="admin-list-item"><div><strong>${esc(r.title)}</strong><br><span class="meta">${esc(r.description)}</span></div><button class="danger-button del-r" data-i="${i}">Delete</button></div>`).join('');document.querySelectorAll('.del-r').forEach(b=>b.onclick=async()=>{if(confirm('Delete record?')){DATA.records.splice(+b.dataset.i,1);await save()}})}
loginForm.onsubmit=async e=>{e.preventDefault();try{await api('login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:adminPassword.value})});loginGate.hidden=true;adminContent.hidden=false;await load()}catch{loginError.hidden=false}}
async function check(){try{await api('auth');loginGate.hidden=true;adminContent.hidden=false;await load()}catch{}}
championForm.onsubmit=async e=>{e.preventDefault();DATA.champion={...DATA.champion,name:cName.value.trim(),event:cEvent.value.trim(),score:cScore.value.trim()};const u=await upload(cImage);if(u)DATA.champion.image=u;await save();alert('Champion saved.')}
addPlayerForm.onsubmit=async e=>{e.preventDefault();const img=await upload(pImage);DATA.players.push({id:slug(pName.value),name:pName.value.trim(),status:pStatus.value.trim()||'Tour Member',points:+pPoints.value||0,wins:+pWins.value||0,seconds:+pSeconds.value||0,majors:+pMajors.value||0,mvp:+pMvp.value||0,image:img,bio:pBio.value.trim(),longBio:pLongBio.value.trim()});await save();e.target.reset();pStatus.value='Tour Member';alert('Player added.')}
epSelect.onchange=loadPlayer;
enSelect.onchange=loadNews;
esSelect.onchange=loadShop;
editPlayerForm.onsubmit=async e=>{e.preventDefault();const p=DATA.players[+epSelect.value];p.status=epStatus.value.trim();p.points=+epPoints.value||0;p.wins=+epWins.value||0;p.seconds=+epSeconds.value||0;p.majors=+epMajors.value||0;p.mvp=+epMvp.value||0;p.bio=epBio.value.trim();p.longBio=epLongBio.value.trim();const img=await upload(epImage);if(img)p.image=img;await save();alert('Player saved.')}
deletePlayer.onclick=async()=>{const i=+epSelect.value;if(confirm('Delete player?')){DATA.players.splice(i,1);await save()}}
tournamentForm.onsubmit=async e=>{e.preventDefault();const img=await upload(tImage);DATA.tournaments.push({id:slug(tName.value),name:tName.value.trim(),course:tCourse.value.trim(),date:tDate.value,type:tType.value,status:tStatus.value,winner:tWinner.value.trim(),score:tScore.value.trim(),image:img});if(img)DATA.gallery.unshift(img);await save();e.target.reset();alert('Tournament added.')}
newsForm.onsubmit=async e=>{e.preventDefault();const img=await upload(nImage);DATA.news.push({id:slug(nHeadline.value),headline:nHeadline.value.trim(),date:nDate.value,summary:nSummary.value.trim(),body:nBody.value.trim(),image:img});await save();e.target.reset();alert('Article published.')}
editNewsForm.onsubmit=async e=>{e.preventDefault();const i=+enSelect.value;const n=DATA.news[i];if(!n)return;n.headline=enHeadline.value.trim();n.date=enDate.value;n.summary=enSummary.value.trim();n.body=enBody.value.trim();const img=await upload(enImage);if(img)n.image=img;await save();enSelect.value=String(Math.min(i,DATA.news.length-1));loadNews();alert('Article updated.')}
deleteNews.onclick=async()=>{const i=+enSelect.value;if(!DATA.news[i])return;if(confirm('Delete this Tour News article? This cannot be undone.')){DATA.news.splice(i,1);await save();alert('Article deleted.')}}
recordForm.onsubmit=async e=>{e.preventDefault();DATA.records.push({id:slug(rTitle.value),title:rTitle.value.trim(),description:rDescription.value.trim()});await save();e.target.reset();alert('Record added.')}
shopForm.onsubmit=async e=>{e.preventDefault();const img=await upload(sImage);DATA.shop.push({id:slug(sName.value),name:sName.value.trim(),price:sPrice.value.trim(),description:sDescription.value.trim(),link:sLink.value.trim(),image:img});await save();e.target.reset();alert('Shop item added.')}
editShopForm.onsubmit=async e=>{e.preventDefault();const i=+esSelect.value;const s=DATA.shop[i];if(!s)return;s.name=esName.value.trim();s.price=esPrice.value.trim();s.description=esDescription.value.trim();s.link=esLink.value.trim();const img=await upload(esImage);if(img)s.image=img;await save();esSelect.value=String(Math.min(i,DATA.shop.length-1));loadShop();alert('Shop item updated.')}
deleteShop.onclick=async()=>{const i=+esSelect.value;if(!DATA.shop[i])return;if(confirm('Delete this shop item? This cannot be undone.')){DATA.shop.splice(i,1);await save();alert('Shop item deleted.')}}
function pollLines(p){return (p&&p.options?p.options:[]).map(o=>typeof o==='string'?o:o.text).join('\n')}
function renderPolls(){ePollSelect.innerHTML=DATA.polls.map((p,i)=>`<option value="${i}">${esc(p.question)}</option>`).join('');loadPoll()}
function loadPoll(){const p=DATA.polls[+ePollSelect.value||0];if(!p){ePollQuestion.value='';ePollOptions.value='';ePollActive.checked=false;return}ePollQuestion.value=p.question||'';ePollOptions.value=pollLines(p);ePollActive.checked=p.active!==false}
ePollSelect.onchange=loadPoll;
pollForm.onsubmit=async e=>{e.preventDefault();const opts=pollOptions.value.split('\n').map(x=>x.trim()).filter(Boolean);if(opts.length<2)return alert('Please enter at least two options.');DATA.polls.push({id:slug(pollQuestion.value),question:pollQuestion.value.trim(),options:opts.map(text=>({text})),votes:{},active:pollActive.checked});await save();e.target.reset();pollActive.checked=true;alert('Poll created.')}
editPollForm.onsubmit=async e=>{e.preventDefault();const p=DATA.polls[+ePollSelect.value];if(!p)return;const opts=ePollOptions.value.split('\n').map(x=>x.trim()).filter(Boolean);if(opts.length<2)return alert('Please enter at least two options.');const before=pollLines(p);const after=opts.join('\n');if(before!==after&&Object.keys(p.votes||{}).length&& !confirm('Changing the options will reset all votes for this poll. Continue?'))return;p.question=ePollQuestion.value.trim();p.active=ePollActive.checked;if(before!==after){p.options=opts.map(text=>({text}));p.votes={}}await save();alert('Poll updated.')}
deletePoll.onclick=async()=>{const i=+ePollSelect.value;if(!DATA.polls[i])return;if(confirm('Delete this poll?')){DATA.polls.splice(i,1);await save();alert('Poll deleted.')}}
function renderMembers(){memberSelect.innerHTML=MEMBERS.map((m,i)=>`<option value="${i}">${esc(m.username)}</option>`).join('');const playerOpts='<option value="">Not linked</option>'+DATA.players.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');memberPlayerId.innerHTML=playerOpts;newMemberPlayerId.innerHTML=playerOpts;loadMember()}
function loadMember(){const m=MEMBERS[+memberSelect.value||0];if(!m){memberUsername.value='';memberId.value='';memberSince.value='';memberStatus.value='';memberCardLevel.value='';memberValidThrough.value='';memberPlayerId.value='';return}memberUsername.value=m.username||'';memberId.value=m.memberId||'';memberSince.value=m.memberSince||'';memberStatus.value=m.status||'Tour Member';memberCardLevel.value=m.cardLevel||'Member';memberValidThrough.value=m.validThrough||'';memberPlayerId.value=m.playerId||'';memberNewPassword.value=''}
memberSelect.onchange=loadMember;
saveMember.onclick=async()=>{const m=MEMBERS[+memberSelect.value];if(!m)return;await api('members',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'update',username:m.username,playerId:memberPlayerId.value,memberId:memberId.value.trim(),memberSince:memberSince.value.trim(),status:memberStatus.value.trim(),cardLevel:memberCardLevel.value.trim(),validThrough:memberValidThrough.value.trim(),newPassword:memberNewPassword.value})});MEMBERS=await api('members',{cache:'no-store'});renderMembers();alert('Member details saved.')}
addMemberForm.onsubmit=async e=>{e.preventDefault();await api('members',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'create',username:newMemberUsername.value.trim(),newPassword:newMemberPassword.value,playerId:newMemberPlayerId.value,memberId:newMemberId.value.trim(),memberSince:newMemberSince.value.trim(),status:newMemberStatus.value.trim(),cardLevel:newMemberCardLevel.value.trim(),validThrough:newMemberValidThrough.value.trim()})});MEMBERS=await api('members',{cache:'no-store'});renderMembers();e.target.reset();newMemberSince.value='2026';newMemberStatus.value='Tour Member';newMemberCardLevel.value='Member';alert('Portal member added.')}


function loadHowItWorks(){const h=DATA.howItWorks||{};howTitle.value=h.title||'How the Tour Works';howIntro.value=h.intro||'';howBody.value=h.body||''}
howItWorksForm.onsubmit=async e=>{e.preventDefault();DATA.howItWorks={title:howTitle.value.trim()||'How the Tour Works',intro:howIntro.value.trim(),body:howBody.value.trim()};await save();alert('How the Tour Works updated.')}
function renderPollResults(){const box=document.getElementById('pollResultsAdmin');if(!box)return;if(!DATA.polls.length){box.innerHTML='<p class="meta">No polls yet.</p>';return}box.innerHTML=DATA.polls.map(p=>{const votes=p.votes||{},total=Object.keys(votes).length;return `<article class="admin-insight-card"><h3>${esc(p.question)}</h3><p class="meta">${total} total vote${total===1?'':'s'}</p>${(p.options||[]).map((o,i)=>{const text=typeof o==='string'?o:o.text,count=Object.values(votes).filter(v=>+v===i).length,pct=total?Math.round(count/total*100):0;return `<div class="result-row"><div style="flex:1"><strong>${esc(text)}</strong><div class="result-bar"><span style="width:${pct}%"></span></div></div><div>${count} (${pct}%)</div></div>`}).join('')}</article>`}).join('')}
function renderAttendanceResults(){const box=document.getElementById('attendanceResultsAdmin');if(!box)return;const ts=DATA.tournaments.filter(t=>t.status!=='completed');if(!ts.length){box.innerHTML='<p class="meta">No upcoming tournaments.</p>';return}box.innerHTML=ts.map(t=>{const map=(DATA.attendance||{})[t.id]||{},vals=Object.values(map),by=s=>vals.filter(x=>x.status===s),chips=a=>a.length?a.map(x=>`<span class="attendance-chip">${esc(x.displayName||x.username)}</span>`).join(''):'<span class="meta">None</span>';return `<article class="admin-insight-card"><h3>${esc(t.name)}</h3><div class="attendance-group"><h4>Going (${by('going').length})</h4>${chips(by('going'))}</div><div class="attendance-group"><h4>Maybe (${by('maybe').length})</h4>${chips(by('maybe'))}</div><div class="attendance-group"><h4>Not Going (${by('not-going').length})</h4>${chips(by('not-going'))}</div></article>`}).join('')}

check();
