let PORTAL=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const dateFmt=s=>s?new Date(s+'T00:00:00').toLocaleDateString('en-AU',{day:'numeric',month:'long',year:'numeric'}):'';
async function pApi(path,opts={}){const r=await fetch('/.netlify/functions/'+path,opts);if(r.status===401)throw new Error('AUTH');if(!r.ok)throw new Error(await r.text());const ct=r.headers.get('content-type')||'';return ct.includes('json')?r.json():r.text()}
function message(t){portalMessage.textContent=t;portalMessage.hidden=false;setTimeout(()=>portalMessage.hidden=true,3500)}
function setupNav(){menuButton.onclick=()=>nav.classList.toggle('open')}
async function loadPortal(){PORTAL=await pApi('portal',{cache:'no-store'});portalLogin.hidden=true;portalContent.hidden=false;renderPortal()}
function renderPortal(){const m=PORTAL.member,p=PORTAL.player;portalWelcome.textContent=p?`Welcome, ${p.name}`:`Welcome, ${m.username}`;const img=p&&p.image?p.image:'images/logo.png';membershipCard.innerHTML=`<div class="membership-card"><img class="membership-photo" src="${esc(img)}" alt="Member photo"><div class="membership-info"><p class="eyebrow">The Travellers Tour</p><h2>${esc(p?p.name:m.username)}</h2><div class="member-fields"><div><small>Member ID</small><strong>${esc(m.memberId||'—')}</strong></div><div><small>Member Since</small><strong>${esc(m.memberSince||'—')}</strong></div><div><small>Status</small><strong>${esc(m.status||'Tour Member')}</strong></div><div><small>Card Level</small><strong>${esc(m.cardLevel||'Member')}</strong></div></div></div></div>`;
if(p){portalStats.innerHTML=[['Season Points',p.points||0],['Wins',p.wins||0],['2nd Places',p.seconds||0],['Majors',p.majors||0],['MVP Points',p.mvp||0]].map(x=>`<div class="portal-stat"><span class="meta">${x[0]}</span><strong>${x[1]}</strong></div>`).join('');profileBio.value=p.bio||'';profileWitb.value=p.witb||'';if(p.image){profilePreview.src=p.image;profilePreview.hidden=false}else profilePreview.hidden=true;profileForm.querySelector('button').disabled=false}else{portalStats.innerHTML='<p class="meta">This login is not linked to a player profile yet. Ask the Tour Admin to link it.</p>';profileBio.value='';profileWitb.value='';profileForm.querySelector('button').disabled=true}
portalAttendance.innerHTML=PORTAL.tournaments.length?PORTAL.tournaments.map(t=>{const own=t.ownAttendance||'';return `<div class="attendance-event"><strong>${esc(t.name)}</strong><div class="meta">${dateFmt(t.date)} · ${esc(t.course)}</div><div class="rsvp-buttons"><button type="button" class="rsvp-button ${own==='going'?'active':''}" data-id="${esc(t.id)}" data-status="going">Going</button><button type="button" class="rsvp-button ${own==='maybe'?'active':''}" data-id="${esc(t.id)}" data-status="maybe">Maybe</button><button type="button" class="rsvp-button ${own==='not-going'?'active':''}" data-id="${esc(t.id)}" data-status="not-going">Not Going</button></div></div>`}).join(''):'<p class="meta">No upcoming events.</p>';
document.querySelectorAll('.rsvp-button').forEach(b=>b.onclick=async()=>{await pApi('portal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'attendance',tournamentId:b.dataset.id,status:b.dataset.status})});await loadPortal();message('Attendance updated.')});
portalPolls.innerHTML=PORTAL.polls.length?PORTAL.polls.map(poll=>`<div class="poll-card"><strong>${esc(poll.question)}</strong><div class="poll-options">${poll.options.map((o,i)=>`<button type="button" class="poll-option ${poll.ownVote===i?'selected':''}" data-poll="${esc(poll.id)}" data-option="${i}"><span>${esc(o.text)}</span><span class="poll-count">${o.count} vote${o.count===1?'':'s'}</span></button>`).join('')}</div></div>`).join(''):'<p class="meta">There are no open polls right now.</p>';
document.querySelectorAll('.poll-option').forEach(b=>b.onclick=async()=>{await pApi('portal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'vote',pollId:b.dataset.poll,optionIndex:+b.dataset.option})});await loadPortal();message('Vote saved.')});}
portalLoginForm.onsubmit=async e=>{e.preventDefault();portalLoginError.hidden=true;try{await pApi('player-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:portalUsername.value.trim(),password:portalPassword.value})});portalPassword.value='';await loadPortal()}catch{portalLoginError.hidden=false}}
profileForm.onsubmit=async e=>{e.preventDefault();let image='';if(profileImage.files[0]){const fd=new FormData();fd.append('file',profileImage.files[0]);const r=await pApi('portal-upload',{method:'POST',body:fd});image=r.url}await pApi('portal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'profile',bio:profileBio.value.trim(),witb:profileWitb.value.trim(),image})});profileImage.value='';await loadPortal();message('Profile updated.')}
portalLogout.onclick=async()=>{await pApi('player-logout',{method:'POST'});location.reload()};
setupNav();loadPortal().catch(()=>{});