let DATA=null;
async function loadData(){const r=await fetch('/.netlify/functions/data',{cache:'no-store'});if(!r.ok)throw new Error('Could not load tour data');DATA=await r.json();return DATA}
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const dateFmt=s=>s?new Date(s+'T00:00:00').toLocaleDateString('en-AU',{day:'numeric',month:'long',year:'numeric'}):'';
const media=src=>src?`<div class="media-frame"><img src="${esc(src)}" alt=""></div>`:`<div class="media-frame"><span class="meta">No photo</span></div>`;
function setupNav(){const b=document.getElementById('menuButton'),n=document.getElementById('nav');if(b&&n)b.onclick=()=>n.classList.toggle('open')}
function tournamentCard(t){return `<article class="card">${media(t.image)}<div class="card-body"><span class="tag">${esc(t.type)}</span><h3>${esc(t.name)}</h3><p class="meta">${esc(t.course)}<br>${dateFmt(t.date)}</p><p><strong>${t.status==='completed'?(t.winner?'Winner: '+esc(t.winner):'Completed'):'Upcoming'}</strong>${t.score?`<br>${esc(t.score)}`:''}</p></div></article>`}
async function init(){setupNav();try{const d=await loadData();
if(document.getElementById('latestChampionName')){latestChampionName.textContent=d.champion.name;latestChampionEvent.textContent=d.champion.event;latestChampionScore.textContent=d.champion.score||'';if(d.champion.image)latestChampionImage.src=d.champion.image}
if(document.getElementById('homeNews'))homeNews.innerHTML=d.news.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,3).map(n=>`<article class="news-card">${media(n.image)}<div class="card-body"><span class="tag">${dateFmt(n.date)}</span><h3>${esc(n.headline)}</h3><p>${esc(n.summary)}</p><a class="button" href="article.html?id=${encodeURIComponent(n.id)}">Read article</a></div></article>`).join('');
if(document.getElementById('standingsBody'))standingsBody.innerHTML=d.players.slice().sort((a,b)=>b.points-a.points).map((p,i)=>`<tr><td>${i+1}</td><td><a href="player.html?id=${encodeURIComponent(p.id)}"><strong>${esc(p.name)}</strong></a></td><td>${p.points||0}</td><td>${p.wins||0}</td><td>${p.seconds||0}</td><td>${p.majors||0}</td></tr>`).join('');
if(document.getElementById('mvpBody'))mvpBody.innerHTML=d.players.slice().sort((a,b)=>(b.mvp||0)-(a.mvp||0)).map((p,i)=>`<tr><td>${i+1}</td><td><a href="player.html?id=${encodeURIComponent(p.id)}"><strong>${esc(p.name)}</strong></a></td><td>${p.mvp||0}</td></tr>`).join('');
if(document.getElementById('playersGrid'))playersGrid.innerHTML=d.players.map(p=>`<article class="card player-card">${media(p.image)}<div class="card-body"><span class="status">${esc(p.status||'Tour Member')}</span><h3>${esc(p.name)}</h3><p class="meta">${p.points||0} points · ${p.wins||0} wins · ${p.majors||0} majors</p><p>${esc(p.bio||'')}</p><a class="button" href="player.html?id=${encodeURIComponent(p.id)}">View profile</a></div></article>`).join('');
if(document.getElementById('playerDetail')){const id=new URLSearchParams(location.search).get('id'),p=d.players.find(x=>x.id===id);if(!p){playerTitle.textContent='Player not found';playerDetail.innerHTML='<p>That player profile could not be found.</p>'}else{playerTitle.textContent=p.name;playerDetail.innerHTML=`<div class="split"><div>${media(p.image)}</div><div><span class="status">${esc(p.status||'Tour Member')}</span><h2>${esc(p.name)}</h2><p class="meta">${p.points||0} season points · ${p.wins||0} wins · ${p.seconds||0} runner-up finishes · ${p.majors||0} majors · ${p.mvp||0} MVP points</p><p>${esc(p.bio||'')}</p></div></div><div class="article-body" style="margin-top:35px">${esc(p.longBio||p.bio||'')}</div>`}}
if(document.getElementById('upcomingGrid')){const u=d.tournaments.filter(t=>t.status!=='completed').sort((a,b)=>a.date.localeCompare(b.date));const c=d.tournaments.filter(t=>t.status==='completed').sort((a,b)=>b.date.localeCompare(a.date));upcomingGrid.innerHTML=u.map(tournamentCard).join('')||'<p>No upcoming tournaments.</p>';completedGrid.innerHTML=c.map(tournamentCard).join('')||'<p>No completed tournaments.</p>'}
if(document.getElementById('recordsGrid'))recordsGrid.innerHTML=d.records.map(r=>`<article class="record-card"><div class="card-body"><h3>${esc(r.title)}</h3><p>${esc(r.description)}</p></div></article>`).join('')||'<p>No event records yet.</p>';
if(document.getElementById('newsGrid'))newsGrid.innerHTML=d.news.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(n=>`<article class="news-card">${media(n.image)}<div class="card-body"><span class="tag">${dateFmt(n.date)}</span><h3>${esc(n.headline)}</h3><p>${esc(n.summary)}</p><a class="button" href="article.html?id=${encodeURIComponent(n.id)}">Read full article</a></div></article>`).join('');
if(document.getElementById('articleBody')){const id=new URLSearchParams(location.search).get('id'),n=d.news.find(x=>x.id===id);if(!n){articleTitle.textContent='Article not found'}else{articleTitle.textContent=n.headline;articleMeta.textContent=dateFmt(n.date);if(n.image){articleImage.src=n.image;articleImage.hidden=false}articleBody.textContent=n.body}}
if(document.getElementById('galleryGrid')){galleryGrid.innerHTML=d.gallery.map(src=>`<div class="gallery-item">${media(src)}</div>`).join('');galleryGrid.querySelectorAll('img').forEach(img=>img.onclick=()=>{lightboxImage.src=img.src;lightbox.hidden=false});closeLightbox.onclick=()=>lightbox.hidden=true;lightbox.onclick=e=>{if(e.target===lightbox)lightbox.hidden=true}}
if(document.getElementById('shopGrid'))shopGrid.innerHTML=d.shop.map(s=>`<article class="shop-card">${media(s.image)}<div class="card-body"><h3>${esc(s.name)}</h3><p><strong>${esc(s.price)}</strong></p><p>${esc(s.description||'')}</p>${s.link?`<a class="button" href="${esc(s.link)}" target="_blank" rel="noopener">Purchase</a>`:'<span class="tag">Contact tour to purchase</span>'}</div></article>`).join('');
}catch(e){document.querySelectorAll('.loading').forEach(x=>x.textContent='Unable to load live data.')}}
init();
